
###
GET http://localhost:3000/api/currentForecast?q=calgary
###
GET http://localhost:3000/api/fiveDayForecast?q=Doha
###

GET http://localhost:3000/api/autoCompleteSearch?q=cal
###
GET http://localhost:3000/api/twelveHoursForecast?q=Calgary